---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - livefire_answerfile.yml
  tasks:
    - name: Check manager status
      nsxt_manager_status:
          hostname: "{{hostname}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: False
          wait_time: 50

    - name: Create T0 logical router
      nsxt_logical_routers:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "t0-infrastructure-SiteA"
        edge_cluster_name: edge-cluster-1-SiteA
        router_type: TIER0
        high_availability_mode: ACTIVE_ACTIVE
        state: "present"
      register: t0

    - name: Create first logical port on EXT1_VLAN LS to connect T0 router
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "T0-Ext1LpA"
        logical_switch_name: "VLAN-Ext1Ls"
        admin_state: UP
        state: "present"
      register: lsp_T0_EXT1a

    - name: Create first logical port on EXT2_VLAN LS to connect T0 router
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "T0-Ext2LpA"
        logical_switch_name: "VLAN-Ext2Ls"
        admin_state: UP
        state: "present"
      register: lsp_T0_EXT2a

    - name: Create second logical port on EXT1_VLAN LS to connect T0 router
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "T0-Ext1LpB"
        logical_switch_name: "VLAN-Ext1Ls"
        admin_state: UP
        state: "present"
      register: lsp_T0_EXT1b

    - name: Create second logical port on EXT2_VLAN LS to connect T0 router
      nsxt_logical_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "T0-Ext2LpB"
        logical_switch_name: "VLAN-Ext2Ls"
        admin_state: UP
        state: "present"
      register: lsp_T0_EXT2b

    - name: Create logical router port on T0 router EN1 to interconnect uplink VLAN EXT1
      nsxt_logical_router_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: LRP-VLAN-Ext1Ls_EN1
        resource_type: LogicalRouterUpLinkPort
        logical_router_id: "{{t0.id}}"
        edge_cluster_member_index: [0]
        linked_logical_switch_port_id:
          target_type: LogicalPort
          target_id:  "{{lsp_T0_EXT1a.id }}"
        subnets:
        - ip_addresses:
          - 192.168.254.13
          prefix_length: 29
        state: "present"

    - name: Create logical router port on T0 router EN2 to interconnect uplink VLAN EXT2
      nsxt_logical_router_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: LRP-VLAN-Ext2Ls_EN2
        resource_type: LogicalRouterUpLinkPort
        logical_router_id: "{{t0.id}}"
        edge_cluster_member_index: [1]
        linked_logical_switch_port_id:
          target_type: LogicalPort
          target_id:  "{{lsp_T0_EXT2a.id }}"
        subnets:
        - ip_addresses:
          - 192.168.254.21
          prefix_length: 29
        state: "present"

    - name: Create logical router port on T0 router EN2 to interconnect uplink VLAN EXT1
      nsxt_logical_router_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: LRP-VLAN-Ext1Ls_EN2
        resource_type: LogicalRouterUpLinkPort
        logical_router_id: "{{t0.id}}"
        edge_cluster_member_index: [1]
        linked_logical_switch_port_id:
          target_type: LogicalPort
          target_id:  "{{lsp_T0_EXT1b.id }}"
        subnets:
        - ip_addresses:
          - 192.168.254.14
          prefix_length: 29
        state: "present"

    - name: Create logical router port on T0 router EN1 to interconnect uplink VLAN EXT2
      nsxt_logical_router_ports:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: LRP-VLAN-Ext2Ls_EN1
        resource_type: LogicalRouterUpLinkPort
        logical_router_id: "{{t0.id}}"
        edge_cluster_member_index: [0]
        linked_logical_switch_port_id:
          target_type: LogicalPort
          target_id:  "{{lsp_T0_EXT2b.id }}"
        subnets:
        - ip_addresses:
          - 192.168.254.22
          prefix_length: 29
        state: "present"
